# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
    ]
