language: python

python:
  - "3.7"
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  - nodeenv -pn latest
  - npm install

script:
  - potaje collectstatic
  - npm run build
  - git archive HEAD -o potaje.tar.gz
  - tar cf potaje-static.tar.gz static/

notifications:
  email: false

addons:
  artifacts: true