language: python

python:
  - "3.7"
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  - nodeenv -pn latest
  - npm install

script:
  - potaje collectstatic
  - npm run build
  - python setup.py sdist

notifications:
  email: false

addons:
  artifacts: true

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true