language: python

python:
  - "3.5"
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  - nodeenv -pn latest
  - npm install

script:
  - potaje collectstatic
  - npm run build
  - git archive HEAD -o potaje.tar.gz
  - tar cf potaje-static.tar.gz static/

notifications:
#  irc:
#    channels: "irc.freenode.org#potaje"
#    template:
#      - "%{repository}@%{branch}: %{message} (%{build_url})"
#    on_success: change
#    on_failure: change
  email: false
