version: '3.1'

services:
  db:
    restart: unless-stopped
    image: postgres:10-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/backup:/backups
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/bin:/root/bin
    environment:
      DB_NAME: potaje
      DB_USER: potaje
      DB_PASS: pass
      DB_SERVICE: db
      DB_PORT: 5432
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - potaje
  backend:
    build: ./
    command: potaje runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/potaje/static
      - ./media:/usr/src/app/potaje/media
    environment:
      DB_URL: psql://potaje:pass@db:5432/potaje
      DEBUG: "True"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - potaje
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/static
      - ./media:/usr/share/nginx/media
    ports:
      - "80:80"
    networks:
      - potaje
    depends_on:
      - backend
networks:
  potaje:
