# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0004_section_order"),
    ]

    operations = [
        migrations.AlterModelOptions(name="section", options={"ordering": ("order",)},),
    ]
