# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0006_section_rendered"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="rendered",
            field=models.TextField(default="", editable=False),
            preserve_default=False,
        ),
    ]
