# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_album_rendered'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='reel',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='reel_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
