# Generated by Django 2.0.6 on 2018-07-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0010_auto_20170616_2047"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="rendered",
            field=models.TextField(default="", editable=False),
            preserve_default=False,
        ),
    ]
